### ISSUE TITLE
lastest tag is not 3.7 on docker hub

### ISSUE THREAD

**Issue by kylesloan** [thiagofigueiro/varnish-alpine-docker#4]
Hello,

When using the "latest" docker tag, I am getting varnish 4.1, and not 5.1.  When changing to tag "3.7", I get varnish 5.2 as expected.

I believe this has to do with the Dockerfile at https://hub.docker.com/r/thiagofigueiro/varnish-alpine-docker/~/dockerfile/ not seeing to sync up correctly with the Docker file at github (which does seem correct).  You can see the one on docker hub as being FROM alpine:3.6

**Comment by davesnx** [comment]
It's being fixed @kylesloan

**Comment by thiagofigueiro** [comment]
Hi, @kylesloan - thanks for reporting it. I'll have a look at it. If you have a fix I'd be happy to accept a PR :)

**Comment by thiagofigueiro** [comment]
Triggered a build on Docker hub and it picked-up the right version.
